# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seg_engine_cpp <- function(x, y, data, bands, power, weighting, normalize, measures, comparison, keep_env, keep_indices, neighbors, search) {
    .Call(`_seg_seg_engine_cpp`, x, y, data, bands, power, weighting, normalize, measures, comparison, keep_env, keep_indices, neighbors, search)
}

seg_indices_env_cpp <- function(data, env, measures, comparison) {
    .Call(`_seg_seg_indices_env_cpp`, data, env, measures, comparison)
}

seg_pycno_cpp <- function(zone_ids, pops, nx, ny, max_iter, converge) {
    .Call(`_seg_seg_pycno_cpp`, zone_ids, pops, nx, ny, max_iter, converge)
}

